Fix: Handle correctly keys on Get/Put Value and Get/Put IPNS.
ipfs/go-delegated-routing pull request #31
Opened 2022-07-06 12:04 UTC by ajnavarro

2022-07-06 17:20 UTC, aschmahmann requested changes

2022-07-06 17:20 UTC, aschmahmann commented on client/store.go
> +	return c.PutIPNS(ctx, []byte(path), val)
We should have a check for if the key is a valid IPNS identifier as in https://github.com/ipfs/go-ipns/blob/f6e884731b943682a432e4719696c21d8f354b9c/record.go#L48-L49.

Whether this lives in the valuestore wrapper or lower in the client seems debatable, either way is fine by me. You can reuse the error if you want or not, doesn't seem a huge deal either way.

2022-07-07 15:43 UTC, BigLep commented
2022-07-07 conversation: in review, focus on making sure we're handling strings properly.

2022-07-07 16:20 UTC, aschmahmann commented on client/putipns.go
> +	_, err := peer.IDFromString(string(id))
I know I pointed you at go-ipns, but the go-libp2p folks want to kill this function anyway  everyone else misusing it https://github.com/libp2p/go-libp2p-core/pull/274.

We can do `IDFromBytes(id)` instead though

2022-07-07 18:16 UTC, Jorropo approved these changes
LGTM

2022-07-07 18:16 UTC, Jorropo commented on client/putipns.go
> +		return fmt.Errorf("invalid peer ID. Error: [%w]", err)
```suggestion
		return fmt.Errorf("invalid peer ID: %w", err)
```

2022-07-07 18:16 UTC, Jorropo commented on client/putipns.go
> +		return nil, fmt.Errorf("invalid peer ID. Error: [%w]", err)
```suggestion
		return nil, fmt.Errorf("invalid peer ID: %w", err)
```

2022-07-07 18:16 UTC, Jorropo commented on client/store.go
> +		return fmt.Errorf("invalid key. Error: [%w]", err)
```suggestion
		return fmt.Errorf("invalid key: %w", err)
```

2022-07-07 18:16 UTC, Jorropo commented on client/store.go
> +		return nil, fmt.Errorf("invalid key. Error: [%w]", err)
```suggestion
		return nil, fmt.Errorf("invalid key: %w", err)
```

2022-07-07 18:16 UTC, Jorropo commented on client/store.go
> +		return nil, fmt.Errorf("invalid key. Error: [%w]", err)
```suggestion
		return nil, fmt.Errorf("invalid key: %w", err)
```

2022-07-07 18:29 UTC, Jorropo approved these changes
LGTM

2022-07-07 18:37 UTC, merged